on: push

jobs:
  annotation:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::error::This is an error"
      - run: echo "::warning::This is a warning"
      - run: echo "::notice::This is a notice"
      # パラメータもいろいろ指定できる (ファイル指定したり)
      - run: echo "::notice file=.github/workflows/annotation.yml::This is a notice with parameters"
